# This is a basic workflow to help you get started with Actions

name: infra setup

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  terraform-init:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.CLOUD_REGION }}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Generate ssh keys
        run: ssh-keygen -f "aws_terraform_key"

      - name: Archive the private key
        uses: actions/upload-artifact@v4
        with:
          name: ssh-private-key
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.2"
          
      - name: Initialize Terraform
        run: terraform init
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: cd /home/runner/work/Terraform/ && ls -ltr
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: ls -ltr && docker --version && pwd && cat /etc/os-release

  terraform-plan-apply:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.CLOUD_REGION }} 
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Validate Terraform
        run: terraform plan
      - name: Validate Terraform
        run: terraform plan
